---
title: "EHD_project"
author: "Chrissy_casey"
date: "December 21, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)  # For map_data. It's just a wrapper; should just use maps.
library(sp)
library(maps)
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'alabama')                 # AL region county data
centroids <- by(df, df$subregion, getLabelPoint)     # Returns list
centroids <- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'alabama')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.4)


```


```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'connecticut')                 # CT region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'connecticut')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.4)
```

```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'delaware')                 # DE region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'delaware')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.4)
```
```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'florida')                 # FL region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'florida')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.4)

```

```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'georgia')                 # GA region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'georgia')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)

```
```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'illinois')                 # IL region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'illinois')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)

```


```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'indiana')                 # IN region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'indiana')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)

```

```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'kentucky')                 #  KY region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'kentucky')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)
```

```{r}
library(ggplot2)
library(maps)

county_df <- map_data('county')  #mappings of counties by state
ky <- subset(county_df, region=="kentucky")   #subset just for KY
ky$county <- ky$subregion
cnames <- aggregate(cbind(long, lat) ~ subregion, data=ky, FUN=mean)

ggplot(ky, aes(long, lat)) +  geom_polygon(aes(group=group), colour='black', fill=NA) +
    geom_text(data=cnames, aes(long, lat, label = subregion), size=2) + coord_map()
```

```{r}
library(ggplot2)
library(maps)

getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'maine')                 # IN region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'maine')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)
```

```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'maryland')                 # IN region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'maryland')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)
```

```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'massachusetts')                 # IN region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'massachusetts')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)
```

```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'michigan')                 # IN region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'michigan')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)
```

```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'mississippi')                 # IN region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'mississippi')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)
```

```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'new hampshire')                 # IN region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'new hampshire')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)
```

```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'new jersey')                 # IN region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'new jersey')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)
```

```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'new york')                 # IN region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'new york')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)
```


```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'north carolina')                 # IN region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'north carolina')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)
```

```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'ohio')                 # IN region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'ohio')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)
```

```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'pennsylvania')                 # IN region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'pennsylvania')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)
```

```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'rhode island')                 # IN region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'rhode island')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)
```

```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'south carolina')                 # IN region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'south carolina')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)
```

```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'tennessee')                 # IN region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'tennessee')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)
```

```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'vermont')                 # IN region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'vermont')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)
```

```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'virginia')                 # IN region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'virginia')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)

va <- map_data('county',"virginia") # we already did this, but we can do it again
gg1 <- ggplot() + 
  geom_polygon(data = va, aes(x=long, y = lat, group = group), fill = "violet", color = "blue") + 
  coord_fixed(1.3)

labs <- data.frame(
  long = c(-78.34953, -76.57298,-80.38793,-78.88976,-77.00542),
  lat = c(36.68226,37.62426,37.16767,37.78480, 37.50263),
  stringsAsFactors = FALSE
  )  

gg1 + 
  geom_point(data = labs, aes(x = long, y = lat), color = "black", size = 5) +
  geom_point(data = labs, aes(x = long, y = lat), color = "yellow", size = 4)

```

```{r}
map('county', 'virginia')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)

va <- map_data('county',"virginia") # we already did this, but we can do it again
gg1 <- ggplot(centroids,aes(centroids$long,centroids$lat), label=centroids$nam) + 
  geom_polygon(data = va, aes(x=long, y = lat, group = group), fill = "violet", color = "blue",label= centroids$nam[1:100]) + 
  coord_fixed(1.3)
gg1

lat<-c(centroids$lat)
long<-c(centroids$long)
centroids$nam<-unique(df$subregion)
names1<-c(centroids$nam)

labs1 <- data.frame(
  long = long,
  lat = lat,
  names = names1,
  stringsAsFactors = FALSE
  ) 

gg1 + geom_point(data = labs1, aes(x = long, y = lat), color = "black", size = .05) 
```

```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'west virginia')                 # IN region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'west virginia')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)
```

```{r}
getLabelPoint <- # Returns a county-named list of label points
function(county) {Polygon(county[c('long', 'lat')])@labpt}

df <- map_data('county', 'wisconsin')                 # IN region county data
centroids<- by(df, df$subregion, getLabelPoint)     # Returns list
centroids<- do.call("rbind.data.frame", centroids)  # Convert to Data Frame
names(centroids) <- c('long', 'lat')                 # Appropriate Header

map('county', 'wisconsin')
text(centroids$long, centroids$lat, rownames(centroids), offset=0, cex=0.7)
```